name: Maverick Cadaverick
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9209308184217662
title: Maverick Cadaverick
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3853534914087504
  lightness: 0.03198287566192448
  saturation: 0.7490956434048712
  rhythmicContrast: 0.0018388491589576006
purpose: []
