name: Maverick Cadaverick
favicon: null
layout_spectrum: 0.90282
typography_spectrum: 0.96736
title: Maverick Cadaverick
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e312c'
    - '#0a1318'
    - '#ece6cc'
    - '#838472'
    - '#cac6ad'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.7490956434048712
  rhythmicContrast: 0.5
purpose: []
